apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-python-app
  namespace: custom-python-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-python-app
  template:
    metadata:
      labels:
        app: custom-python-app
    spec:
      containers:
      - name: custom-python-app
        image: manpreetiitm/custom-python-app:v3
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "postgresql://admin:admin@postgres.db-service.custom-python-app-namespace.svc.cluster.local:5432/newdb"
---
apiVersion: v1
kind: Service
metadata:
  name: custom-python-app
  namespace: custom-python-app-namespace 
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: my-python-app
